# Generated by Django 6.0 on 2026-01-09 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_home_banner_category'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='property_type',
            field=models.ForeignKey(blank=True, help_text='Property type for vendor (Villa, Resort, or Couple Stay). One vendor can have only one property type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='masters.property_type'),
        ),
    ]
