# Generated by Django 5.1.4 on 2025-06-16 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_daycare',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
    ]
