# Generated by Django 5.1.4 on 2025-06-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_daycare_remove_user_is_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='sas@sdd.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
