# Generated by Django 6.0 on 2025-12-26 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('customer', '0001_initial'), ('customer', '0002_initial')]

    initial = True

    dependencies = [
        ('hotel', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='VillaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Check In'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=10)),
                ('booking_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('room_price_per_night', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('villa_price_per_night', models.DecimalField(decimal_places=2, default=0.0, help_text='Villa price per night (for whole villa booking)', max_digits=10)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('child_count', models.PositiveIntegerField()),
                ('is_for_self', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('no_of_rooms', models.IntegerField(default=1)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Room rate * nights', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Service Tax or Other', max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='GST component', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final price to user', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='1% TDS on subtotal', max_digits=10)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='1% TCS on subtotal', max_digits=10)),
                ('hotel_earning', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Cash at Villa'), ('online', 'Online (Razorpay)')], max_length=10, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=15)),
                ('payment_id', models.CharField(blank=True, help_text='Razorpay Payment ID', max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, help_text='Razorpay Order ID', max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Reference ID for reconciliation', max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, help_text='Optional: Leave empty for whole villa booking', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.villa_rooms')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.villa')),
            ],
        ),
        migrations.AddField(
            model_name='supportticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.villabooking'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('method', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], max_length=20)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customer.villabooking')),
            ],
        ),
        migrations.CreateModel(
            name='favouritevilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.villa')),
            ],
            options={
                'unique_together': {('user', 'villa')},
            },
        ),
    ]
