# Generated by Django 6.0 on 2025-12-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_squashed_0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villabooking',
            name='no_of_rooms',
        ),
        migrations.RemoveField(
            model_name='villabooking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='villabooking',
            name='room_price_per_night',
        ),
        migrations.AlterField(
            model_name='villabooking',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Villa rate * nights', max_digits=10),
        ),
    ]
