# Generated by Django 5.1.4 on 2025-06-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_hotelbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Room rate * nights', max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GST component', max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service Tax or Other', max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Final price to user', max_digits=10),
        ),
    ]
