# Generated by Django 6.0 on 2026-01-03 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_villabooking_no_of_rooms_and_more'),
        ('hotel', '0010_villa_mrp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VillaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1 to 5 stars')),
                ('comment', models.TextField(help_text='Review comment/feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Customer who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='villa_reviews', to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(help_text='Villa being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel.villa')),
            ],
            options={
                'verbose_name': 'Villa Review',
                'verbose_name_plural': 'Villa Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'villa')},
            },
        ),
    ]
