# Generated by Django 5.1.4 on 2025-06-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_hotelbooking_base_amount_hotelbooking_gst_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='tax_percent',
            new_name='hotel_earning',
        ),
    ]
