# Generated by Django 5.1.4 on 2025-06-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_tax_percent_hotelbooking_hotel_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='commission_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
