# Generated by Django 6.0 on 2026-01-05 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_villareview'),
        ('hotel', '0010_villa_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='villabooking',
            name='booking_type',
            field=models.CharField(choices=[('whole_villa', 'Whole Villa'), ('selected_rooms', 'Selected Rooms')], default='whole_villa', help_text='Type of booking: whole villa or selected rooms', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of rooms of this type booked')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night for this room at the time of booking', max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_rooms', to='customer.villabooking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.villa_rooms')),
            ],
            options={
                'verbose_name': 'Booking Room',
                'verbose_name_plural': 'Booking Rooms',
                'unique_together': {('booking', 'room')},
            },
        ),
    ]
