# Generated by Django 6.0 on 2026-01-08 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_villabooking_booking_type_bookingroom'),
        ('hotel', '0012_villa_about_villa_specialties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritevilla',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favouritevilla',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room ID for Resort/Couple Stay favorites. Leave null for whole villa favorites.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.villa_rooms'),
        ),
        migrations.AlterUniqueTogether(
            name='favouritevilla',
            unique_together={('user', 'villa', 'room')},
        ),
    ]
