# Generated by Django 6.0 on 2026-01-08 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_favouritevilla_unique_together_and_more'),
        ('masters', '0009_home_banner_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=255)),
                ('phone_number', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('number_of_people', models.PositiveIntegerField(help_text='Number of people attending the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='The event being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='masters.event')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the booking (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Booking',
                'verbose_name_plural': 'Event Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
