# Generated by Django 5.1.4 on 2025-06-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_hotelbooking_tcs_amount_hotelbooking_tds_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=10),
        ),
    ]
