# Generated by Django 6.0 on 2026-01-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_eventbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='villareview',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether the review has been approved by admin'),
        ),
    ]
