# Generated by Django 6.0 on 2026-01-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_villareview_is_approved'),
        ('masters', '0010_room_type_amenities_alter_room_type_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=255)),
                ('check_in', models.DateField(help_text='Check-in date')),
                ('check_out', models.DateField(help_text='Check-out date')),
                ('number_of_guests', models.PositiveIntegerField(help_text='Total number of guests')),
                ('phone_number', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='Location/City for the enquiry', on_delete=django.db.models.deletion.CASCADE, to='masters.city')),
                ('property_type', models.ForeignKey(help_text='Type of property (Villa, Resort, Couple Stay)', on_delete=django.db.models.deletion.CASCADE, to='masters.property_type')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
