# Generated by Django 5.1.4 on 2025-07-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_hotelbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='room_price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
