# Generated by Django 5.1.4 on 2025-07-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_hotelbooking_room_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Check In'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=10),
        ),
    ]
