# Generated by Django 6.0 on 2026-01-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=255)),
                ('enquiry_type', models.CharField(choices=[('corporate_events', 'Corporate Events'), ('wedding_ceremony', 'Wedding Ceremony'), ('birthday_party', 'Birthday Party'), ('retirement_party', 'Retirement Party'), ('other', 'Other')], help_text='Type of event enquiry', max_length=50)),
                ('phone_number', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('check_in_datetime', models.DateTimeField(help_text='Event check-in date and time')),
                ('check_out_datetime', models.DateTimeField(help_text='Event check-out date and time')),
                ('number_of_people', models.PositiveIntegerField(help_text='Number of people for the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Enquiry',
                'verbose_name_plural': 'Event Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
