# Generated by Django 6.0 on 2026-01-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_eventenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='meal_option',
            field=models.CharField(choices=[('with_meal', 'With Meal'), ('without_meal', 'Without Meal')], default='without_meal', help_text='Meal option: With Meal or Without Meal', max_length=20),
        ),
    ]
