# Generated by Django 5.1.4 on 2025-07-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_supportticket_ticketmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='shipment',
            new_name='booking',
        ),
    ]
