# Generated by Django 5.1.4 on 2025-07-22 23:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_favouritehotel'),
        ('hotel', '0027_hotel_is_recommended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritehotel',
            unique_together={('user', 'hotel')},
        ),
    ]
