# Generated by Django 5.1.4 on 2025-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_favouritehotel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
