# Generated by Django 5.1.4 on 2025-07-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_hotelbooking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='room_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
