# Generated by Django 5.1.4 on 2025-08-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_hotelbooking_room_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='child_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
