# Generated by Django 5.1.4 on 2025-08-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_hotelbooking_child_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='no_of_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
