# Generated by Django 5.1.4 on 2025-08-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_hotelbooking_no_of_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room_quantity',
        ),
    ]
