# Generated by Django 5.1.4 on 2025-09-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_remove_hotelbooking_room_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='order_id',
            field=models.CharField(blank=True, help_text='Razorpay Order ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Razorpay Payment ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash at Hotel'), ('online', 'Online (Razorpay)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Reference ID for reconciliation', max_length=100, null=True),
        ),
    ]
