# Generated by Django 5.1.4 on 2025-10-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(default='dsdsd@sd.vom', max_length=254),
            preserve_default=False,
        ),
    ]
