# Generated by Django 6.0 on 2025-12-24 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_hotelbooking_email'),
        ('hotel', '0031_hotel_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='villa_price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Villa price per night (for whole villa booking)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Optional: Leave empty for whole villa booking', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel_rooms'),
        ),
    ]
