# Generated by Django 5.1.4 on 2025-04-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='dog_breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
