# Generated by Django 6.0 on 2025-12-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_rename_room_amenities_villa_rooms_villa_amenities'),
        ('masters', '0003_villa_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room_amenity',
            new_name='villa_amenity',
        ),
    ]
