# Generated by Django 6.0 on 2025-12-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_rename_room_amenity_villa_amenity'),
    ]

    operations = [
        # First rename the field to preserve data
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='feature_image',
        ),
        # Then update the field properties
        migrations.AlterField(
            model_name='event',
            name='feature_image',
            field=models.ImageField(blank=True, help_text='Main/feature image for the event', null=True, upload_to='events/'),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='masters.event')),
            ],
        ),
    ]
