# Generated by Django 5.1.4 on 2025-04-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('age_limit', models.PositiveIntegerField(help_text='Recommended age in weeks/months/years')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
