# Generated by Django 6.0 on 2025-12-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_event_image_event_feature_image_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
    ]
