# Generated by Django 6.0 on 2026-01-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_remove_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Event end date and time', null=True),
        ),
        migrations.AlterField(
            model_name='property_type',
            name='name',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Resort', 'Resort'), ('Couple Stay', 'Couple Stay')], help_text='Type of property', max_length=50, unique=True),
        ),
    ]
