# Generated by Django 6.0 on 2026-01-05 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_event_end_date_alter_property_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room_type',
            options={'verbose_name': 'Room Type', 'verbose_name_plural': 'Room Types'},
        ),
        migrations.AddField(
            model_name='room_type',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Vendor who created this room type. If null, it's a system-wide room type (admin created).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='room_type',
            unique_together={('name', 'user')},
        ),
    ]
