# Generated by Django 6.0 on 2026-01-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_room_type_options_room_type_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_banner',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', help_text='Banner position: Top or Bottom', max_length=10),
        ),
    ]
