# Generated by Django 5.1.4 on 2025-04-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_home_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='symptom_images/'),
        ),
    ]
