# Generated by Django 6.0 on 2026-01-09 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_home_banner_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Room amenities that will be available for this room type', related_name='room_types', to='masters.villa_amenity'),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Vendor who created this room type. Only vendors can create room types.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
