# Generated by Django 6.0 on 2026-01-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_room_type_amenities_alter_room_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='city_logos/'),
        ),
    ]
