# Generated by Django 5.1.4 on 2025-04-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='image',
            field=models.ImageField(default='11dsdsd/sdsdsd', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
