# Generated by Django 6.0 on 2026-01-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_city_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_banner',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('landing_page', 'Landing Page')], default='top', help_text='Banner position: Top, Bottom, or Landing Page', max_length=20),
        ),
    ]
