# Generated by Django 6.0 on 2026-01-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_alter_home_banner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location/City where the event will take place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='masters.city'),
        ),
    ]
