# Generated by Django 5.1.4 on 2025-04-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_product_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='image',
            field=models.ImageField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
