# Generated by Django 5.1.4 on 2025-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_service_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.FloatField(default=1.55),
            preserve_default=False,
        ),
    ]
