# Generated by Django 6.0 on 2026-01-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Location where the event will take place', max_length=255, null=True),
        ),
    ]
