# Generated by Django 5.1.4 on 2025-04-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
