# Generated by Django 5.1.4 on 2025-04-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_vaccination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='price',
            field=models.IntegerField(),
        ),
    ]
