# Generated by Django 5.1.4 on 2025-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_alter_service_price_alter_vaccination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('amount', 'Amount')], default='percent', max_length=10),
        ),
    ]
