# Generated by Django 5.1.4 on 2025-04-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0020_consultation_type_online_consultation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_menu',
            name='price',
        ),
    ]
