# Generated by Django 5.1.4 on 2025-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_remove_food_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='symptom_images/'),
        ),
    ]
