# Generated by Django 5.1.4 on 2025-05-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_vaccination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_banner',
            name='is_for_web',
            field=models.BooleanField(default=False),
        ),
    ]
