# Generated by Django 5.1.4 on 2025-05-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0023_home_banner_is_for_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='image',
        ),
    ]
