# Generated by Django 5.1.4 on 2025-06-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_remove_vaccination_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
