# Generated by Django 5.1.4 on 2025-06-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
