# Generated by Django 5.1.4 on 2025-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_room_amenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='cat_breed',
        ),
        migrations.DeleteModel(
            name='consultation_type',
        ),
        migrations.DeleteModel(
            name='dog_breed',
        ),
        migrations.DeleteModel(
            name='food_menu',
        ),
        migrations.DeleteModel(
            name='online_consultation_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='service_subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='symptom',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='vaccination',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='product_category',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='service_category',
        ),
        migrations.DeleteModel(
            name='service_subcategory',
        ),
    ]
