# Generated by Django 5.1.4 on 2025-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0027_city_delete_cat_breed_delete_consultation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default=1, upload_to='city_images/'),
            preserve_default=False,
        ),
    ]
