# Generated by Django 6.0 on 2025-12-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='amenities/'),
        ),
    ]
