# Generated by Django 6.0 on 2025-12-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_amenity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Event price/amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='itinerary',
            field=models.TextField(blank=True, help_text='Event itinerary/schedule', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
