# Generated by Django 6.0 on 2025-12-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0031_event_amount_event_itinerary_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_markup_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage markup to add to villa prices (e.g., 10 for 10%)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
