"""
Django settings for warangle project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path


import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-t^w1l_qr(&tonib^xf^0_x2qf$ro_=5ia!vb+a+nvujk5j#@%*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "https://vendor.rabbitstay.com",
    "https://rabbitstay.com",
    "https://www.rabbitstay.com",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "masters",
    "customer",
    "hotel",
    "users",
    "rest_framework",
    "corsheaders",
    "drf_yasg",  # Swagger/OpenAPI documentation
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "warangle.middleware.RequestLoggingMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8081",  # React frontend
    "http://localhost:5173",
    "https://rabbit-stay-d121a.web.app",
    "https://rabbitstaybackend.pythonanywhere.com",
    "https://rabbitstay.com",
    "https://rabbitstays.com",
    "https://villaguru.in"
]


HTML2PDF_API_KEY = "IjjR93npHaOZ6bXt6BmHdt2AwYRh3LBoe3hIYz0wBkHddGoa79PF00BB9cgPAdVl"


ROOT_URLCONF = "warangle.urls"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
}


# Ensure a "logs" folder exists in your project root (for local dev)
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(asctime)s: %(levelname)s: %(message)s"},
    },
    "handlers": {
        "request_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            # ✅ Use platform-safe path
            "filename": os.path.join(LOG_DIR, "requests.log"),
            "formatter": "verbose",
        },
        "webhook_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "webhook.log"),
            "formatter": "verbose",
        },
        # Optional console handler (so you also see logs in terminal)
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": True,
        },
        "razorpay_webhook": {
            "handlers": ["webhook_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}


# # firebase_config.py
import os
from firebase_admin import credentials, initialize_app

# Firebase Admin SDK setup
firebase_key_path = os.path.join(BASE_DIR, "warangle", "firebase_key.json")
cred = credentials.Certificate(firebase_key_path)
initialize_app(cred)


RAZORPAY_KEY_ID = "rzp_live_RE2gwnn077s5MX"
RAZORPAY_KEY_SECRET = "A3iDN0SmfqUR2uNHjMROYCHB"
RAZORPAY_WEBHOOK_SECRET = "s8f7s9df87s9df87s9df87s9df87s9df8"

STREAM_API_KEY = "c7wwttj85hg7"
STREAM_API_SECRET = "cgptvrzsttwj9vcebwy25k7y6aqkd6nxh56gkwxhsj3djs989g7k5wraprep926d"


from datetime import timedelta


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=60),
}


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "warangle.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


import os
import socket

# Treat as local when DEBUG is True (makes local dev easier)
# IS_LOCAL = DEBUG or socket.gethostname() in ["LAPTOP-MIDTE91B"]  # your machine name(s)
IS_LOCAL = True

if IS_LOCAL:
    # ✅ Use SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
else:
    # ✅ Use PostgreSQL on production/server
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "rabbitstay",
            "USER": "rabbituser",
            "PASSWORD": "Hardpassword@12",
            "HOST": "localhost",
            "PORT": "5432",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"  # Keep as 'en-us' unless you want Hindi/another language

TIME_ZONE = "Asia/Kolkata"  # ✅ Set Indian time zone

USE_I18N = True
USE_TZ = True  # Recommended: keep True to store in UTC, but display in IST


# settings.py

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"  # or your email provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "Rabbitstay221@gmail.com"
EMAIL_HOST_PASSWORD = "qxacifguvstguift"  # use App Password if using Gmail


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
# Location where `collectstatic` will collect static files for production
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

AUTH_USER_MODEL = "users.User"


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Swagger/OpenAPI Documentation Settings
# SWAGGER_SETTINGS = {
#     'SECURITY_DEFINITIONS': {
#         'Bearer': {
#             'type': 'apiKey',
#             'name': 'Authorization',
#             'in': 'header',
#             'description': 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
#         }
#     },
#     'USE_SESSION_AUTH': False,
#     'JSON_EDITOR': True,
#     'SUPPORTED_SUBMIT_METHODS': [
#         'get',
#         'post',
#         'put',
#         'delete',
#         'patch'
#     ],
#     'OPERATIONS_SORTER': 'alpha',
#     'TAGS_SORTER': 'alpha',
#     'DOC_EXPANSION': 'none',
#     'DEEP_LINKING': True,
#     'SHOW_EXTENSIONS': True,
#     'DEFAULT_MODEL_RENDERING': 'example',
#     'VALIDATOR_URL': None,  # Disable schema validation to prevent errors
# }

# REDOC_SETTINGS = {
#     'LAZY_RENDERING': False,
# }
