# Generated by Django 6.0 on 2025-12-26 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_squashed_0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillaPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night for this specific date', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_pricing', to='hotel.villa')),
            ],
            options={
                'verbose_name': 'Villa Pricing',
                'verbose_name_plural': 'Villa Pricings',
                'ordering': ['date'],
                'unique_together': {('villa', 'date')},
            },
        ),
    ]
