# Generated by Django 5.1.4 on 2025-06-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_description_hotel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='free_cancellation_till',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='total_reviews',
        ),
    ]
