# Generated by Django 6.0 on 2025-12-26 06:43

from django.db import migrations


def rename_m2m_table(apps, schema_editor):
    """Rename the ManyToMany table from room_amenities to villa_amenities"""
    db_alias = schema_editor.connection.alias
    # Check if table exists before renaming
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='hotel_villa_rooms_room_amenities'
        """)
        if cursor.fetchone():
            schema_editor.execute(
                "ALTER TABLE hotel_villa_rooms_room_amenities RENAME TO hotel_villa_rooms_villa_amenities"
            )


def reverse_rename_m2m_table(apps, schema_editor):
    """Reverse: rename back to room_amenities"""
    db_alias = schema_editor.connection.alias
    # Check if table exists before renaming
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='hotel_villa_rooms_villa_amenities'
        """)
        if cursor.fetchone():
            schema_editor.execute(
                "ALTER TABLE hotel_villa_rooms_villa_amenities RENAME TO hotel_villa_rooms_room_amenities"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_villapricing'),
    ]

    operations = [
        migrations.RunPython(rename_m2m_table, reverse_rename_m2m_table),
        migrations.RenameField(
            model_name='villa_rooms',
            old_name='room_amenities',
            new_name='villa_amenities',
        ),
    ]
