# Generated by Django 5.1.4 on 2025-06-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(choices=[('room_only', 'Room Only'), ('breakfast', 'Breakfast Included'), ('breakfast_lunch', 'Breakfast + Lunch'), ('breakfast_dinner', 'Breakfast + Dinner'), ('all_meals', 'Breakfast + Lunch + Dinner')], default='room_only', max_length=50),
        ),
    ]
