# Generated by Django 6.0 on 2025-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_rename_room_amenities_villa_rooms_villa_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='markup_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom markup percentage for this villa (e.g., 10 for 10%). If not set, system-wide markup will be used.', max_digits=5, null=True),
        ),
    ]
