# Generated by Django 5.1.4 on 2025-06-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_room_title'),
        ('masters', '0025_room_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='hotel_rooms',
        ),
    ]
