# Generated by Django 6.0 on 2026-01-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_villa_markup_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='weekend_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage increase for weekend prices (e.g., 25 for 25% increase). Applied to base price on weekends (Friday, Saturday, Sunday).', max_digits=5, null=True),
        ),
    ]
