# Generated by Django 5.1.4 on 2025-06-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rename_room_hotel_rooms'),
        ('masters', '0026_room_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_rooms',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel_rooms',
            name='room_amenities',
            field=models.ManyToManyField(blank=True, to='masters.room_amenity'),
        ),
    ]
