# Generated by Django 6.0 on 2026-01-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_villa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='villa_star_facility',
            field=models.IntegerField(blank=True, choices=[(1, '1 Star Villa'), (2, '2 Star Villa'), (3, '3 Star Villa'), (4, '4 Star Villa'), (5, '5 Star Villa'), (6, '6 Star Villa'), (7, '7 Star Villa')], help_text='Villa star facility type (1-7 Star Villa). This is a facility classification, not a rating.', null=True),
        ),
    ]
