# Generated by Django 5.1.4 on 2025-06-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_hotel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
    ]
