# Generated by Django 6.0 on 2026-01-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_villa_villa_star_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price (MRP) for the villa', max_digits=10, null=True),
        ),
    ]
