# Generated by Django 6.0 on 2026-01-05 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_villa_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night for this specific room and date', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_pricing', to='hotel.villa_rooms')),
            ],
            options={
                'verbose_name': 'Room Pricing',
                'verbose_name_plural': 'Room Pricings',
                'ordering': ['date'],
                'unique_together': {('room', 'date')},
            },
        ),
    ]
