# Generated by Django 5.1.4 on 2025-06-14 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_remove_hotel_city'),
        ('masters', '0027_city_delete_cat_breed_delete_consultation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.city'),
        ),
    ]
