# Generated by Django 6.0 on 2026-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_roompricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='about',
            field=models.TextField(blank=True, help_text='Detailed information about the villa/resort/couple stay property', null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='specialties',
            field=models.TextField(blank=True, help_text='Special features, unique selling points, or specialties of the property', null=True),
        ),
    ]
