# Generated by Django 6.0 on 2026-01-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_villa_about_villa_specialties'),
        ('masters', '0010_room_type_amenities_alter_room_type_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villa_rooms',
            options={'verbose_name': 'Villa Room', 'verbose_name_plural': 'Villa Rooms'},
        ),
        migrations.AddField(
            model_name='villa_rooms',
            name='room_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of physical rooms of this type available in the property'),
        ),
    ]
