# Generated by Django 5.1.4 on 2025-06-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_remove_hotel_price_per_night_alter_hotel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='free_breakfast',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='includes_taxes',
        ),
    ]
