# Generated by Django 5.1.4 on 2025-06-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_remove_hotel_free_breakfast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='is_primary',
        ),
    ]
