# Generated by Django 6.0 on 2026-01-09 08:25

from django.db import migrations
from collections import defaultdict


def consolidate_duplicate_rooms(apps, schema_editor):
    """
    Consolidate duplicate room entries (same villa + room_type) into single entries with room_count.
    """
    VillaRooms = apps.get_model('hotel', 'villa_rooms')
    
    # Try to get BookingRoom model if it exists
    try:
        BookingRoom = apps.get_model('customer', 'BookingRoom')
        has_booking_room = True
    except LookupError:
        has_booking_room = False
    
    # Group rooms by (villa_id, room_type_id)
    room_groups = defaultdict(list)
    for room in VillaRooms.objects.all():
        if room.villa_id and room.room_type_id:
            key = (room.villa_id, room.room_type_id)
            room_groups[key].append(room)
    
    # For each group with duplicates, consolidate
    for (villa_id, room_type_id), rooms in room_groups.items():
        if len(rooms) > 1:
            # Keep the first room as the main one
            main_room = rooms[0]
            other_rooms = rooms[1:]
            
            # Count total rooms
            total_count = len(rooms)
            main_room.room_count = total_count
            main_room.save()
            
            # Update all BookingRoom references to point to main_room if model exists
            if has_booking_room:
                for other_room in other_rooms:
                    # Get all bookings for this other room
                    other_room_bookings = BookingRoom.objects.filter(room_id=other_room.id)
                    
                    for booking_room in other_room_bookings:
                        # Check if main_room already has a booking for this booking
                        existing_booking = BookingRoom.objects.filter(
                            booking_id=booking_room.booking_id,
                            room_id=main_room.id
                        ).first()
                        
                        if existing_booking:
                            # Merge quantities
                            existing_booking.quantity += booking_room.quantity
                            existing_booking.save()
                            booking_room.delete()
                        else:
                            # Just update the room reference
                            booking_room.room_id = main_room.id
                            booking_room.save()
            
            # Delete the duplicate rooms
            for other_room in other_rooms:
                other_room.delete()


def reverse_consolidation(apps, schema_editor):
    """
    Reverse consolidation - split rooms back (not fully reversible, but needed for migration rollback)
    """
    # This is a one-way operation - we can't fully reverse it
    # But we need this function for migration rollback
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_villa_rooms_options_villa_rooms_room_count_and_more'),
    ]

    operations = [
        migrations.RunPython(consolidate_duplicate_rooms, reverse_consolidation),
    ]
