# Generated by Django 5.1.4 on 2025-06-17 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_remove_hotelimage_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_rooms',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.CreateModel(
            name='hotel_roomsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_rooms_gallery/')),
                ('hotel_rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.hotel_rooms')),
            ],
        ),
    ]
