# Generated by Django 6.0 on 2026-01-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_consolidate_duplicate_rooms'),
        ('masters', '0010_room_type_amenities_alter_room_type_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='villa_rooms',
            unique_together={('villa', 'room_type')},
        ),
    ]
