# Generated by Django 5.1.4 on 2025-06-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_hotel_rooms_main_image_hotel_roomsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
    ]
