# Generated by Django 6.0 on 2026-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_add_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='guest_policy',
            field=models.TextField(blank=True, help_text='Guest policy information for the property', null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='room_policy',
            field=models.TextField(blank=True, help_text='Room policy information for the property', null=True),
        ),
    ]
