# Generated by Django 6.0 on 2026-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_villa_guest_policy_room_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomavailability',
            name='is_manually_closed',
            field=models.BooleanField(
                default=False,
                help_text='If True, room is manually closed for this date (vendor override)'
            ),
        ),
    ]
