# Generated by Django 6.0 on 2026-01-13 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_roomavailability_is_manually_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomavailability',
            options={'ordering': ['date', 'room']},
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='available_count',
            field=models.PositiveIntegerField(default=0, help_text='Current available rooms for this date. Automatically calculated from bookings, but can be manually overridden.'),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='hotel.villa_rooms'),
        ),
    ]
