# Generated by Django 5.1.4 on 2025-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_hotel_account_holder_name_hotel_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
