# Generated by Django 5.1.4 on 2025-06-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_hotel_landmark_hotel_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
