# Generated by Django 6.0 on 2026-01-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_alter_roomavailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='max_adults',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of adults the villa can accommodate (for Villa property type filtering)', null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='max_children',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of children the villa can accommodate (for Villa property type filtering)', null=True),
        ),
        migrations.AddField(
            model_name='villa_rooms',
            name='max_adults',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of adults this room can accommodate (for Resort/Couple Stay filtering)', null=True),
        ),
        migrations.AddField(
            model_name='villa_rooms',
            name='max_children',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of children this room can accommodate (for Resort/Couple Stay filtering)', null=True),
        ),
    ]
