# Generated by Django 5.1.4 on 2025-06-30 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_alter_hotel_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_rooms',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel'),
        ),
    ]
