# Generated by Django 5.1.4 on 2025-07-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_alter_hotel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
