# Generated by Django 5.1.4 on 2025-07-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_roomavailability'),
        ('masters', '0029_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.property_type'),
        ),
    ]
