# Generated by Django 5.1.4 on 2025-07-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_hotel_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
