# Generated by Django 5.1.4 on 2025-07-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_hotel_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_rooms',
            name='max_guest_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
