# Generated by Django 5.1.4 on 2025-08-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_hotel_rooms_max_guest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_rooms',
            name='go_live',
            field=models.BooleanField(default=False),
        ),
    ]
