# Generated by Django 5.1.4 on 2025-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_hotel_rooms_go_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_rooms',
            name='go_live',
        ),
        migrations.AddField(
            model_name='hotel',
            name='go_live',
            field=models.BooleanField(default=False),
        ),
    ]
