# Generated by Django 6.0 on 2025-12-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_remove_hotel_rooms_go_live_hotel_go_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Villa price per night (for whole villa booking)', max_digits=10, null=True),
        ),
    ]
