# Generated by Django 6.0 on 2025-12-24 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_hotel_to_villa_data(apps, schema_editor):
    """Delete RoomAvailability records that reference old hotel_rooms"""
    # Since the old hotel_rooms table is being deleted, we need to clean up
    # RoomAvailability records that reference it. They can be recreated later.
    with schema_editor.connection.cursor() as cursor:
        # Delete all RoomAvailability records that reference old hotel_rooms
        # (they'll be recreated when needed)
        cursor.execute("""
            DELETE FROM hotel_roomavailability 
            WHERE room_id IN (SELECT id FROM hotel_hotel_rooms)
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_villabooking_alter_favouritehotel_unique_together_and_more'),
        ('hotel', '0032_data_migration_hotel_to_villa'),
        ('masters', '0031_event_amount_event_itinerary_alter_event_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hotel_rooms',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelimage',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotel_rooms',
            name='room_amenities',
        ),
        migrations.RemoveField(
            model_name='hotel_rooms',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='hotel_roomsimage',
            name='hotel_rooms',
        ),
        migrations.CreateModel(
            name='villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villa_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Budget', 'Budget'), ('Mid_range', 'Mid-range'), ('Premium', 'Premium'), ('Boutique', 'Boutique')], default='Budget', max_length=50)),
                ('no_of_rooms', models.IntegerField()),
                ('address', models.TextField()),
                ('landmark', models.TextField(blank=True, null=True)),
                ('pincode', models.IntegerField()),
                ('star_rating', models.IntegerField(blank=True, null=True)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('go_live', models.BooleanField(default=False)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, help_text='Villa price per night (for whole villa booking)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gst_number', models.CharField(blank=True, help_text='GST Number (15 characters, e.g., 29ABCDE1234F2Z5)', max_length=15, null=True)),
                ('gst_certificate', models.FileField(blank=True, help_text='Upload GST Certificate (PDF/Image)', null=True, upload_to='hotel_docs/gst_certificates/')),
                ('pan_number', models.CharField(blank=True, help_text='PAN Card Number (optional)', max_length=10, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_document', models.FileField(blank=True, help_text='Upload Cancelled Cheque or Bank Passbook (Image/PDF)', null=True, upload_to='hotel_docs/bank_docs/')),
                ('amenities', models.ManyToManyField(blank=True, to='masters.amenity')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.city')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.property_type')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='villa_rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('max_guest_count', models.IntegerField()),
                ('title', models.CharField(choices=[('room_only', 'Room Only'), ('breakfast', 'Breakfast Included'), ('breakfast_lunch', 'Breakfast + Lunch'), ('breakfast_dinner', 'Breakfast + Dinner'), ('all_meals', 'Breakfast + Lunch + Dinner')], default='room_only', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refundable', models.BooleanField(default=True)),
                ('meals_included', models.BooleanField(default=False)),
                ('bed_type', models.CharField(blank=True, max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('view', models.CharField(blank=True, max_length=100)),
                ('room_amenities', models.ManyToManyField(blank=True, to='masters.room_amenity')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='masters.room_type')),
                ('villa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.villa')),
            ],
        ),
        # Data migration: Copy data from old tables to new tables
        migrations.RunPython(
            code=migrate_hotel_to_villa_data,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='villa_roomsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='villa_rooms_gallery/')),
                ('villa_rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.villa_rooms')),
            ],
        ),
        migrations.CreateModel(
            name='VillaAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.villa')),
            ],
            options={
                'unique_together': {('villa', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VillaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='villa_gallery/')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.villa')),
            ],
        ),
        # Data migration: Copy data from old tables to new tables
        migrations.RunPython(
            code=migrate_hotel_to_villa_data,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.villa_rooms'),
        ),
        migrations.DeleteModel(
            name='HotelAvailability',
        ),
        migrations.DeleteModel(
            name='hotel',
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
        migrations.DeleteModel(
            name='hotel_roomsImage',
        ),
        migrations.DeleteModel(
            name='hotel_rooms',
        ),
    ]
